### ISSUE TITLE
[BUG] Extra Song UI's default time label is improperly aligned

### ISSUE THREAD

**Issue by ModestSkillsCH** [Biendeo/My-Clone-Hero-Tweaks#24]
Hi Biendo, when adjusting the alignment of the labels every label apart from time is moved by where the : is, but time is moved based on where T is.

**Comment by Biendeo** [comment]
After further conversation, I have determined that what you are talking about is that the default time label has a space at the end (i.e. it defaults to `Time: `). This means that the alignment doesn't look quite right by default the short term fix would be to change this label in the config. This default will be remedied in future versions.
