### ISSUE TITLE
[BUG] Incorrect note count on a GH2 DLC rip

### ISSUE THREAD

**Issue by GenericMadScientist** [Biendeo/My-Clone-Hero-Tweaks#27]
**Describe the bug**
The note count on Hard guitar for You've Got Another Thing Comin' from the current GH2 DLC rips is incorrect.

**To Reproduce**
1. Set up a song with this mid: [notes.zip](https://github.com/Biendeo/My-Clone-Hero-Tweaks/files/5294231/notes.zip)
2. Play it on Hard guitar
3. Display the note total with ExtraSongUI
4. Observe it says 805 notes

**Expected behavior**
It should be 803 notes, as it says when you finish the song or FC it.

**Environment:**
 - OS: Windows 10
 - Clone Hero Version v0.23.2.2
 - Using the new Clone Hero Launcher [no]
 - Tweak version v1.4.0.23

**Comment by Biendeo** [comment]
I can't seem to recreate it on the current development branch, I'll close this on the next release.
![](https://i.imgur.com/dfyQOJe.png)
