### ISSUE TITLE
[BUG] Not being able to hit any notes or get the mods to work after installing

### ISSUE THREAD

**Issue by FrederikPos** [Biendeo/My-Clone-Hero-Tweaks#29]
**Describe the bug**
So when I download all the mods on bepinex Including LegacyModLoader run the command and play the game none of the mods work and i cant hit any of the notes

1. Download All Mods & Some Tweaks Like GC Fretedit etc.
2. Launch the game when all mods are in Bepinex/plugins And all tweaks are in the Tweaks folder directory
3. Play Any Chart
4. Try To Hit Notes And See You Cant

**Expected behavior**
IDK

**Environment (please complete the following information):**
 - OS: macOS
 - Clone Hero Version: v23.2.2
 - Using the new Clone Hero Launcher: No
 - Tweak version: v1.5.1

**Additional context**
None

**Comment by Biendeo** [comment]
What version of BepInEx are you using? Can you paste the `BepInEx\LogOutput.log` file?

**Comment by havemorefaith** [comment]
i use the latest bepinex version and here is my LogOutput.log file: [Message:   BepInEx] Chainloader ready
[Message:   BepInEx] Chainloader started
[Info   :   BepInEx] 6 plugins to load
[Info   :   BepInEx] Loading [Biendeo CH Lib 1.5.1]
[Info   :   BepInEx] Loading [Accuracy Indicator 1.5.1]
[Info   :   BepInEx] Loading [Combo Indicator 1.5.1]
[Info   :   BepInEx] Loading [Extra Song UI 1.5.1]
[Info   :   BepInEx] Loading [Legacy Mod Loader 1.5.1]
[Info   :Legacy Mod Loader] Found mod FretEdit, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
[Info   :Legacy Mod Loader] Found mod GameColors, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
[Info   :Legacy Mod Loader] Found mod MoveScoreCounter, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
[Info   :Legacy Mod Loader] Loaded mod FretEdit, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
[Info   :Legacy Mod Loader] Loaded mod GameColors, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
[Info   :Legacy Mod Loader] Loaded mod MoveScoreCounter, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
[Info   :   BepInEx] Loading [Splash Text Editor 1.5.1]
[Message:   BepInEx] Chainloader startup complete

**Comment by Biendeo** [comment]
The very very latest version of BepInEx (5.4) has a regression which breaks the mods. Try using 5.3.

**Comment by havemorefaith** [comment]
nope still broken

**Comment by Biendeo** [comment]
Can you change `BepInEx\config\BepInEx.cfg` where it's got under the header: `Logging.Disk` and change `LogLevels` to `LogLevels = All`, then re-run the game and paste the full log?

**Comment by havemorefaith** [comment]
so here is my LogOutput.log file again after editing the config file: [Message:   BepInEx] Chainloader ready
[Message:   BepInEx] Chainloader started
[Info   :   BepInEx] 6 plugins to load
[Info   :   BepInEx] Loading [Biendeo CH Lib 1.5.1]
[Debug  :Biendeo CH Lib] Initialising wrapper BaseGuitarPlayerWrapper
[Debug  :Biendeo CH Lib] Loaded method BaseGuitarPlayerWrapper.hitNoteMethod
[Debug  :Biendeo CH Lib] Initialising wrapper BarrelRollWrapper
[Debug  :Biendeo CH Lib] Initialising wrapper SpNeckRendererWrapper
[Debug  :Biendeo CH Lib] Initialising wrapper CameraShakeWrapper
[Debug  :Biendeo CH Lib] Initialising wrapper CountdownWrapper
[Debug  :Biendeo CH Lib] Initialising wrapper BaseNeckControllerWrapper
[Debug  :Biendeo CH Lib] Initialising wrapper HighwayScrollWrapper
[Debug  :Biendeo CH Lib] Initialising wrapper HealthContainerWrapper
[Debug  :Biendeo CH Lib] Initialising wrapper ComboColorWrapper
[Debug  :Biendeo CH Lib] Initialising wrapper BaseNoteRendererWrapper
[Debug  :Biendeo CH Lib] Initialising wrapper BasePlayerWrapper
[Debug  :Biendeo CH Lib] Loaded field BasePlayerWrapper.noteRendererField
[Debug  :Biendeo CH Lib] Loaded field BasePlayerWrapper.gameManagerField
[Debug  :Biendeo CH Lib] Loaded field BasePlayerWrapper.neckControllerField
[Debug  :Biendeo CH Lib] Loaded field BasePlayerWrapper.cameraField
[Debug  :Biendeo CH Lib] Loaded field BasePlayerWrapper.comboCounterField
[Debug  :Biendeo CH Lib] Loaded field BasePlayerWrapper.healthContainerField
[Debug  :Biendeo CH Lib] Loaded field BasePlayerWrapper.fcIndicatorField
[Debug  :Biendeo CH Lib] Loaded field BasePlayerWrapper.soloCounterField
[Debug  :Biendeo CH Lib] Loaded field BasePlayerWrapper.countdownField
[Debug  :Biendeo CH Lib] Loaded field BasePlayerWrapper.unknownTextField
[Debug  :Biendeo CH Lib] Loaded field BasePlayerWrapper.playerField
[Debug  :Biendeo CH Lib] Loaded field BasePlayerWrapper.spBarField
[Debug  :Biendeo CH Lib] Loaded field BasePlayerWrapper.highwayObjectsField
[Debug  :Biendeo CH Lib] Loaded field BasePlayerWrapper.basePointsPerNoteField
[Debug  :Biendeo CH Lib] Loaded field BasePlayerWrapper.highwayScrollField
[Debug  :Biendeo CH Lib] Loaded field BasePlayerWrapper.cameraShakeField
[Debug  :Biendeo CH Lib] Loaded field BasePlayerWrapper.barrelRollField
[Debug  :Biendeo CH Lib] Loaded field BasePlayerWrapper.notesField
[Debug  :Biendeo CH Lib] Loaded field BasePlayerWrapper.frontHitWindowField
[Debug  :Biendeo CH Lib] Loaded field BasePlayerWrapper.backHitWindowField
[Debug  :Biendeo CH Lib] Loaded field BasePlayerWrapper.unknownFloat3Field
[Debug  :Biendeo CH Lib] Loaded field BasePlayerWrapper.hitWindowLengthField
[Debug  :Biendeo CH Lib] Loaded field BasePlayerWrapper.noteToBePlayedField
[Debug  :Biendeo CH Lib] Loaded field BasePlayerWrapper.fretsHeldField
[Debug  :Biendeo CH Lib] Loaded field BasePlayerWrapper.isPlayingField
[Debug  :Biendeo CH Lib] Loaded field BasePlayerWrapper.canOverstrumField
[Debug  :Biendeo CH Lib] Loaded field BasePlayerWrapper.isSPActiveField
[Debug  :Biendeo CH Lib] Loaded field BasePlayerWrapper.isStreakNotActiveField
[Debug  :Biendeo CH Lib] Loaded field BasePlayerWrapper.isSoloActiveField
[Debug  :Biendeo CH Lib] Loaded field BasePlayerWrapper.firstNoteMissedField
[Debug  :Biendeo CH Lib] Loaded field BasePlayerWrapper.unknownBool1Field
[Debug  :Biendeo CH Lib] Loaded field BasePlayerWrapper.unknownBool4Field
[Debug  :Biendeo CH Lib] Loaded field BasePlayerWrapper.soloIndexField
[Debug  :Biendeo CH Lib] Loaded field BasePlayerWrapper.isEarningStarPowerField
[Debug  :Biendeo CH Lib] Loaded field BasePlayerWrapper.multiplierField
[Debug  :Biendeo CH Lib] Loaded field BasePlayerWrapper.starPowersHitField
[Debug  :Biendeo CH Lib] Loaded field BasePlayerWrapper.notesSeenField
[Debug  :Biendeo CH Lib] Loaded field BasePlayerWrapper.hittableNotesField
[Debug  :Biendeo CH Lib] Loaded field BasePlayerWrapper.spAmountField
[Debug  :Biendeo CH Lib] Loaded field BasePlayerWrapper.healthField
[Debug  :Biendeo CH Lib] Loaded field BasePlayerWrapper.healthGainField
[Debug  :Biendeo CH Lib] Loaded field BasePlayerWrapper.healthDrainField
[Debug  :Biendeo CH Lib] Loaded field BasePlayerWrapper.healthGainInSPField
[Debug  :Biendeo CH Lib] Loaded field BasePlayerWrapper.comboField
[Debug  :Biendeo CH Lib] Loaded field BasePlayerWrapper.hittableNotesThisFrameName
[Debug  :Biendeo CH Lib] Loaded field BasePlayerWrapper.scoreField
[Debug  :Biendeo CH Lib] Loaded field BasePlayerWrapper.highestComboField
[Debug  :Biendeo CH Lib] Loaded field BasePlayerWrapper.hitNotesField
[Debug  :Biendeo CH Lib] Loaded field BasePlayerWrapper.unknownInt6Field
[Debug  :Biendeo CH Lib] Loaded field BasePlayerWrapper.spNeckRendererField
[Debug  :Biendeo CH Lib] Loaded method BasePlayerWrapper.missNoteMethod
[Debug  :Biendeo CH Lib] Loaded method BasePlayerWrapper.overStrumMethod
[Debug  :Biendeo CH Lib] Initialising wrapper BassAudioManagerWrapper
[Debug  :Biendeo CH Lib] Loaded field BassAudioManagerWrapper.instanceField
[Debug  :Biendeo CH Lib] Loaded field BassAudioManagerWrapper.menuSongField
[Info   :   BepInEx] Loading [Accuracy Indicator 1.5.1]
[Debug  :Accuracy Indicator] Initialising patches with class HitNoteHandler
[Debug  :Accuracy Indicator] Found matching method for patch BaseGuitarPlayerWrapper.HitNote
[Debug  :Accuracy Indicator] Found postfix method Postfix
[Debug  :Accuracy Indicator] Initialising patches with class MissNoteHandler
[Debug  :Accuracy Indicator] Found matching method for patch BasePlayerWrapper.MissNote
[Debug  :Accuracy Indicator] Found postfix method Postfix
[Info   :   BepInEx] Loading [Combo Indicator 1.5.1]
[Info   :   BepInEx] Loading [Extra Song UI 1.5.1]
[Debug  :Extra Song UI] Initialising patches with class HitNoteHandler
[Debug  :Extra Song UI] Found matching method for patch BaseGuitarPlayerWrapper.HitNote
[Debug  :Extra Song UI] Found prefix method Prefix
[Debug  :Extra Song UI] Found postfix method Postfix
[Debug  :Extra Song UI] Initialising patches with class MissNoteHandler
[Debug  :Extra Song UI] Found matching method for patch BasePlayerWrapper.MissNote
[Debug  :Extra Song UI] Found postfix method Postfix
[Debug  :Extra Song UI] Initialising patches with class OverStrumHandler
[Debug  :Extra Song UI] Found matching method for patch BasePlayerWrapper.OverStrum
[Debug  :Extra Song UI] Found postfix method Postfix
[Info   :   BepInEx] Loading [Legacy Mod Loader 1.5.1]
[Info   :Legacy Mod Loader] Found mod FretEdit, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
[Info   :Legacy Mod Loader] Found mod GameColors, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
[Info   :Legacy Mod Loader] Found mod MoveScoreCounter, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
[Info   :Legacy Mod Loader] Loaded mod FretEdit, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
[Info   :Legacy Mod Loader] Loaded mod GameColors, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
[Info   :Legacy Mod Loader] Loaded mod MoveScoreCounter, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
[Info   :   BepInEx] Loading [Splash Text Editor 1.5.1]
[Message:   BepInEx] Chainloader startup complete
[Debug  :Biendeo CH Lib] Lato-Regular

**Comment by Biendeo** [comment]
That's quite odd, the Biendeo CH Lib method loading seems to stop really early. LegacyModLoader should be okay as it doesn't utilise it, but the other mods probably panic later on. Can you try using the debug version of Biendeo CH Lib and seeing if there's a different log output?

**Comment by havemorefaith** [comment]
the log output seems to be the same

**Comment by Biendeo** [comment]
Can you paste the log at the top before the `Chainloader started` portion?

**Comment by havemorefaith** [comment]
[Message:   BepInEx] Chainloader ready

**Comment by Biendeo** [comment]
There should be more before, for example:
```
[Message:   BepInEx] BepInEx 5.4.1.0 - Clone Hero
[Info   :   BepInEx] Running under Unity v2018.4.13.4816648
[Info   :   BepInEx] CLR runtime version: 4.0.30319.42000
[Info   :   BepInEx] Supports SRE: True
[Info   :   BepInEx] System platform: Bits64, Windows
[Message:   BepInEx] Preloader started
[Info   :   BepInEx] 1 patcher plugin loaded
[Info   :   BepInEx] Patching [UnityEngine.CoreModule] with [BepInEx.Chainloader]
[Message:   BepInEx] Preloader finished
[Message:   BepInEx] Chainloader ready
[Message:   BepInEx] Chainloader started
```

**Comment by havemorefaith** [comment]
dont have that in mine

**Comment by Biendeo** [comment]
Are there any log messages that occur after `Lato-Regular` or are you unable to interact with the game further?

**Comment by havemorefaith** [comment]
After Lato-Regular in the log there's no more stuff and I cannot just hit notes but everything else I can do in the game

**Comment by Biendeo** [comment]
That's odd, I'd expect there to be some ongoing exceptions thrown every frame afterwards. Can you try removing all the BepInEx plugins but Biendeo CH Lib (you can just move them out of the `plugins` folder for the moment. You can leave the `Tweaks` in place. Does it log initialising more wrappers after `BassAudioManagerWrapper`?

**Comment by havemorefaith** [comment]
No, it does not log initialising more wrappers after BassAudioManagerWrapper

**Comment by balls69** [comment]
Is it a mac with apple's M1 chip in it? Because currently there's a few hiccups now trying to convert x86 programs over to Apple's new architecture. That could be part of the problem; if it is not an Apple silicon Mac then try  a fresh install by redownloading clone hero and copying your files. That seems like the best stop gap solution until this gets resolved. If it is apple silicon it might be a wait it out till apple's implementation f running x86 programs gets better.

**Comment by havemorefaith** [comment]
I don't play Clone hero anymore.
